INSERT IGNORE INTO species (name)
VALUES ('Perro'),
    ('Gato'),
    ('Conejo'),
    ('Hámster'),
    ('Cobaya'),
    ('Hurón'),
    ('Ave'),
    ('Canario'),
    ('Periquito'),
    ('Loro'),
    ('Pez'),
    ('Tortuga'),
    ('Iguana'),
    ('Serpiente'),
    ('Camaleón'),
    ('Caballo'),
    ('Burro'),
    ('Vaca'),
    ('Oveja'),
    ('Cabra'),
    ('Cerdo'),
    ('Gallina'),
    ('Pato'),
    ('Ganso'),
    ('Paloma'),
    ('Erizo'),
    ('Chinchilla'),
    ('Rata'),
    ('Ratón'),
    ('Llama'),
    ('Alpaca'),
    ('Ciervo'),
    ('Zorro'),
    ('Mapache'),
    ('Tigre'),
    ('León'),
    ('Elefante'),
    ('Mono'),
    ('Delfín'),
    ('Foca'),
    ('Caballito de mar'),
    ('Pingüino'),
    ('Ser humano (medicina comparativa)'),
    ('Otros');

INSERT IGNORE INTO roles (role_name)
VALUES ('USER'),
    ('VET'),
    ('ADMIN');